### ISSUE TITLE
怎么实现发光的效果

### ISSUE THREAD

**Issue by yiwuxue** [dinuscxj/CircleProgressBar#1]
怎么实现边缘发光的效果
![xxxx](https://cloud.githubusercontent.com/assets/747325/16763668/75aa12a0-485c-11e6-8364-a4e6607e4fae.jpg)

**Comment by dinuscxj** [comment]
@yiwuxue 如果你想快点实现这个效果的话可以使用BitmapShader实现。让设计师做一个类似的icon 然后给paint设置shader就可以啦。 我过一段时间有空了会用代码实现这个效果

**Comment by dinuscxj** [comment]
可以添加下面的属性实现
1. padding 
       android:paddingLeft="5dp"
       android:paddingTop="5dp"
       android:paddingRight="5dp"
       android:paddingBottom="5dp"

2. blur 效果
        app:progress_blur_radius="5dp"
        app:progress_blur_style="solid"
