### ISSUE TITLE
CircleProgressBar继承ProgressBar,但是并没有啊？

### ISSUE THREAD

**Issue by zhujunhua2012** [dinuscxj/CircleProgressBar#10]
readme里面刚开始介绍，“CircleProgressBar继承ProgressBar”， 但是CircleProgressBar这个是继承的View啊。。。

**Comment by dinuscxj** [comment]
很抱歉， 这个在上一个版本， 最新版本已经移除，感觉必要性不大， 就改成了View， 稍后更新一下wiki
