### ISSUE TITLE
Is it possible to make only the progress_background_color behind the stroke color transparent and the rest of the progress_background_color colored?

### ISSUE THREAD

**Issue by sharmanirudh** [dinuscxj/CircleProgressBar#12]
Thanks for such a nice library, I have used it in many projects. I want to set the only the background color behind the stroke color transparent and the rest as it is.

Thank you in advance.

**Comment by dinuscxj** [comment]
if you both set progress_start_color and progress_end_color to the same color (unless the color is Translucent),   is it what you want ?

**Comment by sharmanirudh** [comment]
Sorry for late response. I want something like this.

![web 1920 2](https://user-images.githubusercontent.com/26672724/43000432-04f4b104-8c3f-11e8-8024-65e8ae8fa703.png)

**Comment by dinuscxj** [comment]
upgrade gradle dependency to 
```gradle 
    implementation 'com.dinuscxj:circleprogressbar:1.3.0'
```
and add the following attribute to your xml 
```xml
       app:drawBackgroundOutsideProgress="true"
        app:progress_background_color="{your color}"
        app:progress_start_color="@android:color/transparent"
        app:progress_end_color="@android:color/transparent"
```

**Comment by sharmanirudh** [comment]
Worked like a charm ☀️😊. Thanks a lot for your awesome 👌 support and library 👍👏.
