### ISSUE TITLE
setProgressBackgroundColor(), setProgressStartColor(), setProgressEndColor() do not seem to be working

### ISSUE THREAD

**Issue by dhinchakrajat** [dinuscxj/CircleProgressBar#13]
Hi @dinuscxj, thanks for this nice library. However, I think that setProgressBackgroundColor(), setProgressStartColor(), setProgressEndColor() are not working.
I am trying to set color like this:
```
mCircleProgressBar.setDrawBackgroundOutsideProgress(true);
mCircleProgressBar.setProgressBackgroundColor(R.color.colorCircularProgressBarBackground);
mCircleProgressBar.setProgressStartColor(R.color.colorBlack);
mCircleProgressBar.setProgressEndColor(R.color.colorBlack);
```
Thanks in advance.

**Comment by dinuscxj** [comment]
On Java code,   what you should set is ColorInt format
```java
Context.getResources().getColor()
```

**Comment by sharmanirudh** [comment]
`Context.getResources().getColor()` is deprecated from Marshmallow so you should use

`ContextCompat.getColor(context, R.color.color_name)`

This will choose the Marshmallow two parameter method or the pre-Marshmallow method appropriately.

So your code will be
```
mCircleProgressBar.setDrawBackgroundOutsideProgress(true);
mCircleProgressBar.setProgressBackgroundColor(ContextCompat.getColor(context, R.color.colorCircularProgressBarBackground));
mCircleProgressBar.setProgressStartColor(ContextCompat.getColor(context, R.color.colorBlack));
mCircleProgressBar.setProgressEndColor(ContextCompat.getColor(context, R.color.colorBlack));
```
