### ISSUE TITLE
Adding animtion.

### ISSUE THREAD

**Issue by HannahShulman** [dinuscxj/CircleProgressBar#20]
Thank you for this project. I would like to know if it's possible to add setting progress with animation.
Thanks in advance,

**Comment by dinuscxj** [comment]
@HannahShulman 
can you show the animation what you'd like to add to the progress?

**Comment by HannahShulman** [comment]
Id like the duration of progress to take some time. If I set animation duration to 1000, then the progress from zero to 100 will take one second, and from zero to 10 will take a tenth of a second. Thanks.
@dinuscxj

**Comment by dinuscxj** [comment]
It's easy to customize yourself ValueAnimator: 

eg: 
```java
     ValueAnimator animator = ValueAnimator.ofInt(0, 100);
        animator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
            @Override
            public void onAnimationUpdate(ValueAnimator animation) {
                int progress = (int) animation.getAnimatedValue();
                myCircleProgressBar.setProgress(progress);   
            }
        });
        // here
        animator.setInterpolator(new LinearInterpolator())
        animator.setDuration(1000);
        animator.start();
```
