### ISSUE TITLE
set indeterminate to true not working

### ISSUE THREAD

**Issue by Sirvanalie** [dinuscxj/CircleProgressBar#6]
Thanks for great library. After search a lot, I found this. But now I want to use animation for progressbar, like indeterminate. When set indeterminate to true, not working. Why ? I want to implementation progressbar like Telegram app. Thanks again bro.

**Comment by lo-g** [comment]
Same here, I'm switching between indeterminated and determinated but indeterminated is not working! Thanks.

**Comment by dinuscxj** [comment]
I am sorry,  CircleProgressBar does not support the properties of the ProgressBar,  
and in release 1.2.0,  the CircleProgressBar has changed the parent to View
