### ISSUE TITLE
style这个属性重复了

### ISSUE THREAD

**Issue by scrylove** [dinuscxj/CircleProgressBar#9]
/res/merged/debug/values/values.xml
Error:(754) Attribute "style" already defined with incompatible format.
Error:(575) Original attribute defined here.
Error:(754) Attribute "style" already defined with incompatible format.
Error:(575) Original attribute defined here.

**Comment by dinuscxj** [comment]
这个应该是你的build.gradle的配置问题， 之前有一个用户跟你一样， 他是compileSdkVersion 和下面的support 包的版本一直导致的
